name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # You might want to update this to a newer Node version if possible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn" # This built-in caching replaces the separate cache action

      # If you still need manual cache control, use the v4 version
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      #
      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - run: yarn test

      - name: Build & Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          REACT_APP_API: https://adminchouettos.lachouettecoop.fr
          REACT_APP_METABASE_API: https://prerapports.lachouettecoop.fr/public/dashboard/0eee5d66-f0ec-4c79-b506-d0d4a82b9e11?code-barres_%28sur_votre_carte%29=
          REACT_APP_MAIL_BDM: bureau-des-membres@lachouettecoop.fr
          REACT_APP_MAIL_COMMISSION_PARTICIPATION: commission_participation_lcc@framalistes.org
          REACT_APP_MAIL_SUPPORT: supportparticipation@lachouettecoop.fr
          REACT_APP_MAIL_EMERGENCY_CASHIER: caisse.b2958f0dc1af85540d9fabb6edf58788.show-sender@streams.zulipchat.com
          REACT_APP_BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
          REACT_APP_COMMIT: ${{ github.sha }}
          REACT_APP_AUTHOR: ${{ github.actor }}
