name: Déploiement continu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@1.12
        with:
          name: lachouettecoop/planning
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
